<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxfoNwe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxfoNwe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxfoNwe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxfoNwe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxfoNwe\App_KernelDevDebugContainer([
    'container.build_hash' => 'TxfoNwe',
    'container.build_id' => '37ce71c4',
    'container.build_time' => 1580994657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxfoNwe');
